font_family JetBrains Mono

fallback_fonts   Vazirmatn

font_size 10
adjust_line_height 2
cursor_shape block
cursor_trail 1
cursor_trail_decay 0.1 0.2
window_padding_width 3
confirm_os_window_close -1
enable_audio_bell no
dynamic_background_opacity no

# add color theme
include Hybrid.conf
